@Entry
@Component
struct Index {
  @State message: string = 'Hello World';

  build() {
   //  元素按照水平方向排列
   // Row({space:35}){
    //    //   Text("space :35").fontSize(14).fontColor(Color.Black)
    //    //   Row().width("10%").height(150).backgroundColor(Color.Red)
    //    //   Row().width("10%").height(150).backgroundColor(Color.Red)
    //    //   Row().width("10%").height(150).backgroundColor(Color.Red)
    //    //
    //    // }
    //    //  .height('90%')
    //    //  .width('100%')

    // Column({space:24}){
    //   Column().width(150).height("10%").backgroundColor(Color.Black)
    //   Column().width(150).height("10%").backgroundColor(Color.Black)
    //   Column().width(150).height("10%").backgroundColor(Color.Black)
    // }.height("100%")
    //   .width("100%")




  }
}